var loci = {
  "1": [2, 6, 7, 9, 10],
  "2": [1, 3],
  "3": [1, 2, 4, 8, 9, 10],
  "4": [3, 5, 6],
  "5": [2, 4, 6, 7, 8],
  "6": [3, 4, 7],
  "7": [1, 2, 5, 6, 8, 9],
  "8": [5, 7, 10],
  "9": [10],
  "10": [1, 3, 4, 5, 8, 9]
};

var locus_words = {
  "1": ["nation", "stay", "songlines", "population", "warfare", "intend", "dispossession", "maintain", "fight", "colonists", "knowledges", "custodians", "years", "resources", "faith", "massacres", "destroys", "decimate", "peacefully", "diplomacy"],
  "2": ["burning", "woodland", "burnt", "root", "forest", "ancient", "potato", "tuberous", "abundance", "surrounded", "plants", "sheep", "harvesting", "raw", "sustainably", "herb", "alight", "grassy", "summer", "daisy"],
  "3": ["wood", "spears", "axes", "stone", "canoes", "thick", "blades", "birds", "shields", "habitat", "home", "species", "cut", "gnarled", "carrying", "tools", "majestic", "sharp", "greenstone", "quarry"],
  "4": ["anthropological", "societies", "religious", "attitudes", "ethnographic", "research", "kinship", "evolutionary", "beliefs", "ethical", "practices", "reciprocity", "studies", "principle", "trusting", "books", "document", "descriptions", "friendship", "biology"],
  "5": ["government", "work", "institute", "historic", "self-sufficient", "thriving", "spirit", "programs", "legacy", "initiatives", "autonomy", "parliamentary", "campaigned", "original", "son", "redress", "nephew", "tirelessly", "denying", "visionary"],
  "6": ["language", "children", "learn", "play", "sing", "settlers", "adults", "prepare", "whisper", "nest", "sleep", "English", "laugh", "winter", "joke", "hunt", "hibernate", "shout", "schooled", "reawakened"],
  "7": ["remains", "burial", "reburied", "museum", "scientific", "discovery", "repatriation", "grave", "legal", "skull", "returned", "removed", "skeletal", "hundreds", "archaeologist", "collection", "sanctioned", "size", "amateur", "illegally"],
  "8": ["skin", "cloak", "care", "white", "smell", "cold", "possum", "bite", "understanding", "wrap", "phrase", "shoulders", "gather", "blankets", "smoke", "grub", "represent", "fever", "responsibilty", "scented"],
  "9": ["creek", "beneath", "drains", "slope", "flows", "wetlands", "upstream", "shallow", "meandering", "wildflowers", "street", "cool", "valley", "feet", "clear", "trap", "roads", "spring", "bush", "swimming"],
  "10": ["truly", "hope", "together", "walk", "walking", "listening", "future", "pride", "map", "modern", "corner", "impacts", "nonindigenous", "resilience", "laneways", "students", "changes", "dramatic", "classes", "traffic"]
};

var special_words = {
  "1": {
    "target": ["ngurungaeta"],
    "foil": ["Murnong"]
  },
  "2": {
    "target": ["Sheoak"],
    "foil": ["Kulin"]
  },
  "3": {
    "target": ["Wil-im-ee Moor-ing"],
    "foil": ["Arrente"]
  },
  "4": {
    "target": ["Frank Gillen"],
    "foil": ["Corranderrk"]
  },
  "5": {
    "target": ["Murrup"],
    "foil": ["Alice Springs"]
  },
  "6": {
    "target": ["Bunjil"],
    "foil": ["Simon Wonga"]
  },
  "7": {
    "target": ["Dhungala"],
    "foil": ["Djeri"]
  },
  "8": {
    "target": ["Manna Gum"],
    "foil": ["Murray River"]
  },
  "9": {
    "target": ["Birrarung"],
    "foil": ["Womin-Djerring"]
  },
  "10": {
    "target": ["Ngang-gak"],
    "foil": ["Yarra River"]
  }
};

var words_ids = {
  "106": ["nation"],
  "221": ["burning"],
  "324": ["wood"],
  "408": ["anthropological"],
  "526": ["government"],
  "621": ["language"],
  "709": ["remains"],
  "845": ["skin"],
  "903": ["creek"],
  "1053": ["truly"],
  "135": ["stay"],
  "204": ["woodland"],
  "327": ["spears"],
  "411": ["societies"],
  "518": ["work"],
  "633": ["children"],
  "711": ["burial"],
  "846": ["cloak"],
  "969": ["beneath"],
  "1051": ["hope"],
  "157": ["songlines"],
  "229": ["burnt"],
  "334": ["axes"],
  "428": ["religious"],
  "506": ["institute"],
  "634": ["learn"],
  "738": ["reburied"],
  "826": ["care"],
  "971": ["drains"],
  "1034": ["together"],
  "145": ["population"],
  "244": ["root"],
  "335": ["stone"],
  "442": ["attitudes"],
  "542": ["historic"],
  "631": ["play"],
  "746": ["museum"],
  "801": ["white"],
  "924": ["slope"],
  "1040": ["walk"],
  "142": ["warfare"],
  "206": ["forest"],
  "323": ["canoes"],
  "407": ["ethnographic"],
  "527": ["self-sufficient"],
  "626": ["sing"],
  "716": ["scientific"],
  "833": ["smell"],
  "933": ["flows"],
  "1054": ["walking"],
  "134": ["intend"],
  "220": ["ancient"],
  "310": ["thick"],
  "456": ["research"],
  "531": ["thriving"],
  "655": ["settlers"],
  "717": ["discovery"],
  "842": ["cold"],
  "918": ["wetlands"],
  "1032": ["listening"],
  "146": ["dispossession"],
  "252": ["potato"],
  "336": ["blades"],
  "430": ["kinship"],
  "509": ["spirit"],
  "645": ["adults"],
  "747": ["repatriation"],
  "844": ["possum"],
  "960": ["upstream"],
  "1052": ["future"],
  "133": ["maintain"],
  "238": ["tuberous"],
  "315": ["birds"],
  "443": ["evolutionary"],
  "551": ["programs"],
  "603": ["prepare"],
  "713": ["grave"],
  "841": ["bite"],
  "908": ["shallow"],
  "1049": ["pride"],
  "150": ["fight"],
  "241": ["abundance"],
  "328": ["shields"],
  "429": ["beliefs"],
  "549": ["legacy"],
  "632": ["whisper"],
  "733": ["legal"],
  "820": ["understanding"],
  "932": ["meandering"],
  "1003": ["map"],
  "103": ["colonists"],
  "205": ["surrounded"],
  "312": ["habitat"],
  "458": ["ethical"],
  "552": ["initiatives"],
  "613": ["nest"],
  "723": ["skull"],
  "843": ["wrap"],
  "949": ["wildflowers"],
  "1011": ["modern"],
  "122": ["knowledges"],
  "239": ["plants"],
  "339": ["home"],
  "427": ["practices"],
  "516": ["autonomy"],
  "639": ["sleep"],
  "736": ["returned"],
  "815": ["phrase"],
  "926": ["street"],
  "1028": ["corner"],
  "110": ["custodians"],
  "264": ["sheep"],
  "313": ["species"],
  "460": ["reciprocity"],
  "543": ["parliamentary"],
  "647": ["English"],
  "745": ["removed"],
  "849": ["shoulders"],
  "941": ["cool"],
  "1045": ["impacts"],
  "114": ["years"],
  "256": ["harvesting"],
  "321": ["cut"],
  "409": ["studies"],
  "540": ["campaigned"],
  "629": ["laugh"],
  "708": ["skeletal"],
  "828": ["gather"],
  "909": ["valley"],
  "1063": ["nonindigenous"],
  "130": ["resources"],
  "249": ["raw"],
  "311": ["gnarled"],
  "459": ["principle"],
  "502": ["original"],
  "601": ["winter"],
  "729": ["hundreds"],
  "857": ["blankets"],
  "940": ["feet"],
  "1050": ["resilience"],
  "125": ["faith"],
  "228": ["sustainably"],
  "329": ["carrying"],
  "417": ["trusting"],
  "523": ["son"],
  "630": ["joke"],
  "728": ["archaeologist"],
  "836": ["smoke"],
  "955": ["clear"],
  "1022": ["laneways"],
  "143": ["massacres"],
  "254": ["herb"],
  "326": ["tools"],
  "435": ["books"],
  "553": ["redress"],
  "625": ["hunt"],
  "707": ["collection"],
  "806": ["grub"],
  "963": ["trap"],
  "1039": ["students"],
  "137": ["destroys"],
  "219": ["alight"],
  "302": ["majestic"],
  "424": ["document"],
  "510": ["nephew"],
  "611": ["hibernate"],
  "706": ["sanctioned"],
  "853": ["represent"],
  "970": ["roads"],
  "1006": ["changes"],
  "144": ["decimate"],
  "203": ["grassy"],
  "333": ["sharp"],
  "433": ["descriptions"],
  "541": ["tirelessly"],
  "622": ["shout"],
  "725": ["size"],
  "839": ["fever"],
  "948": ["spring"],
  "1005": ["dramatic"],
  "131": ["peacefully"],
  "209": ["summer"],
  "350": ["greenstone"],
  "422": ["friendship"],
  "515": ["denying"],
  "646": ["schooled"],
  "727": ["amateur"],
  "824": ["responsibilty"],
  "945": ["bush"],
  "1041": ["classes"],
  "126": ["diplomacy"],
  "243": ["daisy"],
  "338": ["quarry"],
  "405": ["biology"],
  "539": ["visionary"],
  "650": ["reawakened"],
  "742": ["illegally"],
  "835": ["scented"],
  "959": ["swimming"],
  "1038": ["traffic"],
  "153": ["ngurungaeta"],
  "265": ["Sheoak"],
  "349": ["Wil-im-ee Moor-ing"],
  "466": ["Frank Gillen"],
  "555": ["Murrup"],
  "657": ["Bunjil"],
  "753": ["Dhungala"],
  "863": ["Manna Gum"],
  "976": ["Birrarung"],
  "1061": ["Ngang-gak"],
  "267": ["Murnong"],
  "156": ["Kulin"],
  "468": ["Arrente"],
  "557": ["Corranderrk"],
  "467": ["Alice Springs"],
  "559": ["Simon Wonga"],
  "862": ["Djeri"],
  "754": ["Murray River"],
  "1055": ["Womin-Djerring"],
  "977": ["Yarra River"]
}