var loci = {
  "1": [2, 6, 7, 9, 10],
  "2": [1, 3],
  "3": [1, 2, 4, 8, 9, 10],
  "4": [3, 5, 6],
  "5": [2, 4, 6, 7, 8],
  "6": [3, 4, 7],
  "7": [1, 2, 5, 6, 8, 9],
  "8": [5, 7, 10],
  "9": [10],
  "10": [1, 3, 4, 5, 8, 9]
};

var loci_special_foils = {
  "1": [2],
  "2": [1],
  "3": [4],
  "4": [5],
  "5": [4],
  "6": [5],
  "7": [8],
  "8": [7],
  "9": [10],
  "10": [9]
};

var locus_words = {
  "1": ["nation", "songlines", "population", "warfare", "intend", "dispossession", "maintain", "fight", "colonists", "knowledges", "custodians", "resources", "faith", "massacres", "destroys", "decimate", "peacefully", "diplomacy", "treaty", "visitors"],
  "2": ["burning", "woodland", "burnt", "root", "forest", "ancient", "potato", "tuberous", "abundance", "surrounded", "plants", "sheep", "harvesting", "raw", "sustainably", "herb", "alight", "grassy", "summer", "daisy"],
  "3": ["wood", "spears", "axes", "stone", "canoes", "thick", "blades", "birds", "shields", "habitat", "home", "species", "cut", "gnarled", "carrying", "tools", "majestic", "sharp", "greenstone", "quarry"],
  "4": ["anthropological", "societies", "religious", "attitudes", "ethnographic", "research", "kinship", "evolutionary", "beliefs", "ethical", "practices", "reciprocity", "studies", "principle", "trusting", "books", "document", "descriptions", "friendship", "biology"],
  "5": ["government", "work", "institute", "self-sufficient", "thriving", "spirit", "programs", "legacy", "initiatives", "autonomy", "parliamentary", "campaigned", "original", "son", "redress", "nephew", "tirelessly", "lobbying", "denying", "visionary"],
  "6": ["language", "children", "learn", "play", "sing", "settlers", "adults", "prepare", "whisper", "nest", "sleep", "English", "laugh", "winter", "joke", "hunt", "hibernate", "shout", "schooled", "reawakened"],
  "7": ["remains", "burial", "reburied", "museum", "scientific", "discovery", "repatriation", "grave", "legal", "skull", "returned", "removed", "skeletal", "hundreds", "archaeologist", "collection", "sanctioned", "size", "amateur", "illegally"],
  "8": ["skin", "cloak", "white", "smell", "cold", "possum", "bite", "wrap", "shoulders", "gather", "blankets", "smoke", "grub", "represent", "responsibilty", "scented", "meager", "fever", "congestion", "unwell"],
  "9": ["creek", "beneath", "drains", "slope", "flows", "wetlands", "upstream", "shallow", "meandering", "wildflowers", "cool", "valley", "feet", "clear", "trap", "roads", "spring", "bush", "swimming", "migratory"],
  "10": ["hope", "together", "walk", "walking", "listening", "future", "pride", "map", "modern", "corner", "impacts", "nonindigenous", "resilience", "laneways", "students", "changes", "dramatic", "classes", "traffic", "oculus"]
};

var special_words = {
  "1": {
    "target": ["ngurungaeta"],
    "foil": ["Murnong"]
  },
  "2": {
    "target": ["Sheoak"],
    "foil": ["Kulin"]
  },
  "3": {
    "target": ["Wil-im-ee Moor-ing"],
    "foil": ["Arrente"]
  },
  "4": {
    "target": ["Frank Gillen"],
    "foil": ["Corranderrk"]
  },
  "5": {
    "target": ["Murrup"],
    "foil": ["Alice Springs"]
  },
  "6": {
    "target": ["Bunjil"],
    "foil": ["Simon Wonga"]
  },
  "7": {
    "target": ["Dhungala"],
    "foil": ["Djeri"]
  },
  "8": {
    "target": ["Manna Gum"],
    "foil": ["Murray River"]
  },
  "9": {
    "target": ["Birrarung"],
    "foil": ["Womin-Djerring"]
  },
  "10": {
    "target": ["Ngang-gak"],
    "foil": ["Yarra River"]
  }
};

var words_ids = {
  "nation": [106],
  "burning": [221],
  "wood": [324],
  "anthropological": [408],
  "government": [526],
  "language": [621],
  "remains": [709],
  "skin": [845],
  "creek": [903],
  "hope": [1051],
  "songlines": [157],
  "woodland": [204],
  "spears": [327],
  "societies": [411],
  "work": [518],
  "children": [633],
  "burial": [711],
  "cloak": [846],
  "beneath": [969],
  "together": [1034],
  "population": [145],
  "burnt": [229],
  "axes": [334],
  "religious": [428],
  "institute": [506],
  "learn": [634],
  "reburied": [738],
  "white": [801],
  "drains": [971],
  "walk": [1040],
  "warfare": [142],
  "root": [244],
  "stone": [335],
  "attitudes": [442],
  "self-sufficient": [527],
  "play": [631],
  "museum": [746],
  "smell": [833],
  "slope": [924],
  "walking": [1054],
  "intend": [134],
  "forest": [206],
  "canoes": [323],
  "ethnographic": [407],
  "thriving": [531],
  "sing": [626],
  "scientific": [716],
  "cold": [842],
  "flows": [933],
  "listening": [1032],
  "dispossession": [146],
  "ancient": [220],
  "thick": [310],
  "research": [456],
  "spirit": [509],
  "settlers": [655],
  "discovery": [717],
  "possum": [844],
  "wetlands": [918],
  "future": [1052],
  "maintain": [133],
  "potato": [252],
  "blades": [336],
  "kinship": [430],
  "programs": [551],
  "adults": [645],
  "repatriation": [747],
  "bite": [841],
  "upstream": [960],
  "pride": [1049],
  "fight": [150],
  "tuberous": [238],
  "birds": [315],
  "evolutionary": [443],
  "legacy": [549],
  "prepare": [603],
  "grave": [713],
  "wrap": [843],
  "shallow": [908],
  "map": [1003],
  "colonists": [103],
  "abundance": [241],
  "shields": [328],
  "beliefs": [429],
  "initiatives": [552],
  "whisper": [632],
  "legal": [733],
  "shoulders": [849],
  "meandering": [932],
  "modern": [1011],
  "knowledges": [122],
  "surrounded": [205],
  "habitat": [312],
  "ethical": [458],
  "autonomy": [516],
  "nest": [613],
  "skull": [723],
  "gather": [828],
  "wildflowers": [949],
  "corner": [1028],
  "custodians": [110],
  "plants": [239],
  "home": [339],
  "practices": [427],
  "parliamentary": [543],
  "sleep": [639],
  "returned": [736],
  "blankets": [857],
  "cool": [941],
  "impacts": [1045],
  "resources": [130],
  "sheep": [264],
  "species": [313],
  "reciprocity": [460],
  "campaigned": [540],
  "English": [647],
  "removed": [745],
  "smoke": [836],
  "valley": [909],
  "nonindigenous": [1063],
  "faith": [125],
  "harvesting": [256],
  "cut": [321],
  "studies": [409],
  "original": [502],
  "laugh": [629],
  "skeletal": [708],
  "grub": [806],
  "feet": [940],
  "resilience": [1050],
  "massacres": [143],
  "raw": [249],
  "gnarled": [311],
  "principle": [459],
  "son": [523],
  "winter": [601],
  "hundreds": [729],
  "represent": [853],
  "clear": [955],
  "laneways": [1022],
  "destroys": [137],
  "sustainably": [228],
  "carrying": [329],
  "trusting": [417],
  "redress": [553],
  "joke": [630],
  "archaeologist": [728],
  "responsibilty": [824],
  "trap": [963],
  "students": [1039],
  "decimate": [144],
  "herb": [254],
  "tools": [326],
  "books": [435],
  "nephew": [510],
  "hunt": [625],
  "collection": [707],
  "scented": [835],
  "roads": [970],
  "changes": [1006],
  "peacefully": [131],
  "alight": [219],
  "majestic": [302],
  "document": [424],
  "tirelessly": [541],
  "hibernate": [611],
  "sanctioned": [706],
  "meager": [856],
  "spring": [948],
  "dramatic": [1005],
  "diplomacy": [126],
  "grassy": [203],
  "sharp": [333],
  "descriptions": [433],
  "lobbying": [525],
  "shout": [622],
  "size": [725],
  "fever": [839],
  "bush": [945],
  "classes": [1041],
  "treaty": [124],
  "summer": [209],
  "greenstone": [350],
  "friendship": [422],
  "denying": [515],
  "schooled": [646],
  "amateur": [727],
  "congestion": [838],
  "swimming": [959],
  "traffic": [1038],
  "visitors": [128],
  "daisy": [243],
  "quarry": [338],
  "biology": [405],
  "visionary": [539],
  "reawakened": [650],
  "illegally": [742],
  "unwell": [827],
  "migratory": [972],
  "oculus": [1024],
  "ngurungaeta": [153],
  "Sheoak": [265],
  "Wil-im-ee Moor-ing": [349],
  "Frank Gillen": [466],
  "Murrup": [555],
  "Bunjil": [657],
  "Dhungala": [753],
  "Manna Gum": [863],
  "Birrarung": [976],
  "Ngang-gak": [1061],
  "Murnong": [267],
  "Kulin": [156],
  "Arrente": [468],
  "Corranderrk": [557],
  "Alice Springs": [467],
  "Simon Wonga": [559],
  "Djeri": [862],
  "Murray River": [754],
  "Womin-Djerring": [1055],
  "Yarra River": [977]
}